# -*- coding: utf-8 -*-
"""Assignment_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aR7rreOFFHcAgDSL3L9YFXvrHEyLdBhK

# **Task 1: Implement RC4 Encryption and Decryption**
"""

def KeySchAlgo(key):
    key_length = len(key)
    S = list(range(256))
    j = 0
    for i in range(256):
        j = (j + S[i] + key[i % key_length]) % 256
        S[i], S[j] = S[j], S[i]
    return S

def PRGA(S, text_length):
    i = j = 0
    keystream = []
    for _ in range(text_length):
        i = (i + 1) % 256
        j = (j + S[i]) % 256
        S[i], S[j] = S[j], S[i]
        keystream.append(S[(S[i] + S[j]) % 256])
    return keystream

def generate_keystream(key, text_length):
    key = [ord(c) for c in key]
    S = KeySchAlgo(key)
    return PRGA(S, text_length)

def RC4_encrypt(key, plaintext):
    keystream = generate_keystream(key, len(plaintext))
    return bytes([plaintext[i] ^ keystream[i] for i in range(len(plaintext))])

def RC4_decrypt(key, ciphertext):
    return RC4_encrypt(key, ciphertext)  # XORing again restores the original text

key = input("Enter the encryption key: ")
plaintext = input("Enter the plaintext: ").encode()
ciphertext = RC4_encrypt(key, plaintext)
decrypted_text = RC4_decrypt(key, ciphertext)

print("\nCiphertext (Hex):", ciphertext.hex())
print("Decrypted Text:", decrypted_text.decode())

"""# **Task 2: Effect of Key Variations**"""

def bitwise_difference(a, b):
    return sum(bin(x ^ y).count('1') for x, y in zip(a, b))

key = input("Enter the encryption key: ")
plaintext = input("Enter the plaintext: ").encode()
ciphertext = RC4_encrypt(key, plaintext)
decrypted_text = RC4_decrypt(key, ciphertext)

print("\nCiphertext:", ciphertext.hex())
print("Decrypted Text:", decrypted_text.decode())


print("\nTask 2: Effect of Key Variations")
modified_key = input("Enter a slightly modified key (one-bit variation): ")
ciphertext_modified = RC4_encrypt(modified_key, plaintext)

print("Original Ciphertext:", ciphertext.hex())
print("Modified Ciphertext:", ciphertext_modified.hex())
bit_diff = bitwise_difference(ciphertext, ciphertext_modified)
print(f"Bitwise difference between ciphertexts: {bit_diff} bits")

"""# **Task 3: Effect of Plaintext Variations**"""

key = input("Enter the encryption key: ")
plaintext = input("Enter the plaintext: ").encode()
ciphertext = RC4_encrypt(key, plaintext)
decrypted_text = RC4_decrypt(key, ciphertext)

print("\nCiphertext:", ciphertext.hex())
print("Decrypted Text:", decrypted_text.decode())

#Effect of Plaintext Variations
print("\nTask 3: Effect of Plaintext Variations")
plaintext_variation = input("Enter a slightly modified plaintext: ").encode()
ciphertext_variation = RC4_encrypt(key, plaintext_variation)

print("Ciphertext for Original Plaintext:", ciphertext.hex())
print("Ciphertext for Modified Plaintext:", ciphertext_variation.hex())
bit_diff_plaintext = bitwise_difference(ciphertext, ciphertext_variation)
print(f"Bitwise difference between ciphertexts due to plaintext variation: {bit_diff_plaintext} bits")

"""# **Task 4: Strength Analysis and Report**"""

import math
from collections import Counter
import time

def measure_time(func, key, text):
    start_time = time.time()
    func(key, text)
    return time.time() - start_time

def calculate_entropy(data):
    frequency = Counter(data)
    probabilities = [count / len(data) for count in frequency.values()]
    return -sum(p * math.log2(p) for p in probabilities)

def measure_time(func, key, text):
    start_time = time.time()
    func(key, text)
    return time.time() - start_time

key = input("Enter an 8-character key: ")
if len(key) != 8:
    print("Key must be exactly 8 characters.")
    exit()

for _ in range(3):
    size = int(input("Enter plaintext size: "))
    plaintext = input(f"Enter plaintext of size {size}: ")
    if len(plaintext) != size:
        print(f"Error: Plaintext must be exactly {size} characters.")
        exit()

    plaintext_encoded = plaintext.encode()
    encryption_time = measure_time(RC4_encrypt, key, plaintext_encoded)
    ciphertext = RC4_encrypt(key, plaintext_encoded)
    entropy = calculate_entropy(ciphertext)

    print(f"\nPlaintext Size: {size} bytes")
    print(f"Ciphertext: {ciphertext.hex()}")
    print(f"Entropy: {entropy:.4f}")
    print(f"Encryption Time: {encryption_time:.6f} seconds")

"""# **SUMMARY REPORT**

This task involves implementing the RC4 encryption algorithm in Python.

A slight change in the key can lead to significant differences in the ciphertext, a phenomenon known as the avalanche effect. Flipping a single bit in the key results in a drastically different ciphertext. Additionally, examining how minor changes in plaintext affect the ciphertext with a fixed key shows that even small adjustments produce entirely different ciphertexts.

## **Impact of Key Length and Plaintext Patterns on RC4 Security**

Shorter keys are susceptible to brute force attacks. Repeated plaintext patterns can generate predictable ciphertexts, increasing the likelihood of key recovery attacks.

## **RC4's Weaknesses Compared to Modern Ciphers Like AES**

- **AES** offers stronger security with key sizes of 128, 192, or 256 bits, along with multiple encryption rounds for enhanced protection.
- Unlike RC4, **AES** resists cryptographic attacks through its robust diffusion and confusion properties.
- **AES's** larger key sizes make it significantly more resilient to brute force attempts, whereas RC4's smaller keys and inherent biases increase the risk of key recovery attacks.

## **Why RC4 is Weak**

- The key schedule algorithm has structural flaws, leading to biases in the generated keystream.
- Keystream reuse makes RC4 highly vulnerable to known plaintext attacks.
- **Fluhrer-Mantin-Shamir (FMS) Attack:** This attack exploits weaknesses in the initial keystream bytes to extract parts of the encryption key.

"""