# -*- coding: utf-8 -*-
"""assignment_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuHSpYNAT158WN1s33znkgSKYC6uc8Yk
"""

!pip install pycryptodome

"""**Task 1: Implement AES Encryption and Decryption**"""

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
import base64

# Use a fixed 256-bit (32-byte) AES key
key = b'ABCDEF0123456789ABCDEF9876543210'  # 32-byte key for AES-256

def encrypt_aes(plaintext, key):
    cipher = AES.new(key, AES.MODE_CBC, iv=b'\x00' * 16)  # Fixed IV (for reproducibility)
    ciphertext = cipher.encrypt(pad(plaintext.encode(), AES.block_size))
    return base64.b64encode(ciphertext).decode()  # Encode Ciphertext to Base64

def decrypt_aes(ciphertext_b64, key):
    ciphertext = base64.b64decode(ciphertext_b64)  # Decode Base64
    cipher = AES.new(key, AES.MODE_CBC, iv=b'\x00' * 16)  # Same fixed IV
    plaintext = unpad(cipher.decrypt(ciphertext), AES.block_size)
    return plaintext.decode()

# Example usage
plaintext = input("Enter text: ")
ciphertext = encrypt_aes(plaintext, key)
decrypted_text = decrypt_aes(ciphertext, key)

print(f"Ciphertext in Base64: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")

"""**Task 2: Effect of Key Variations**

"""

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
import binascii

def aes_encrypt(text, key):
    cipher = AES.new(key, AES.MODE_ECB)
    padded_text = pad(text.encode(), AES.block_size)
    return cipher.encrypt(padded_text)

def byte_difference(ct1, ct2):
    return sum(b1 != b2 for b1, b2 in zip(ct1, ct2))

plaintext = input("Enter plaintext: ")
key1 = input("Enter a 16-character key: ").encode()

if len(key1) != 16:
    print("Error: Key must be 16 characters long!")
    exit()

key2 = key1[::-1]  # Reverse key order

ct1 = aes_encrypt(plaintext, key1)
ct2 = aes_encrypt(plaintext, key2)

diff = byte_difference(ct1, ct2)

print("\nCiphertext 1:", binascii.hexlify(ct1).decode())
print("Ciphertext 2:", binascii.hexlify(ct2).decode())
print("Different Bytes:", diff)

"""AES encryption is highly sensitive to changes in the key, a phenomenon known as the **avalanche effect**.
- Flipping a single bit in the key results in a drastically different ciphertext.
- This ensures strong security, making it difficult for attackers to predict or decipher the original message.

This property highlights AES's robustness, ensuring even minor changes in input lead to completely different outputs.

**Task 3: Effect of Plaintext Variations**
"""

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
import binascii

def aes_encrypt(text, key):
    cipher = AES.new(key, AES.MODE_ECB)
    padded_text = pad(text.encode(), AES.block_size)
    return cipher.encrypt(padded_text)

def count_bit_difference(ct1, ct2):
    return sum(bin(b1 ^ b2).count('1') for b1, b2 in zip(ct1, ct2))

text1 = input("Enter first plaintext: ")
text2 = input("Enter second plaintext: ")
key = input("Enter a 16-character key: ").encode()

if len(key) != 16:
    print("Error: Key must be 16 characters long!")
    exit()

ct1 = aes_encrypt(text1, key)
ct2 = aes_encrypt(text2, key)

bit_diff = count_bit_difference(ct1, ct2)

print("\nCiphertext 1:", binascii.hexlify(ct1).decode())
print("Ciphertext 2:", binascii.hexlify(ct2).decode())
print("Bitwise Difference:", bit_diff, "bits")

"""**Task 4: Strength Analysis and Report**

"""

import time
import math
from Crypto.Cipher import DES
import binascii
from Crypto.Util.Padding import pad

def des_encrypt(plaintext, key):
    cipher = DES.new(key, DES.MODE_ECB)
    padded_plaintext = pad(plaintext.encode(), DES.block_size)
    ciphertext = cipher.encrypt(padded_plaintext)
    return ciphertext

def calculate_entropy(data):
    freq = {char: data.count(char) for char in set(data)}
    length = len(data)
    return -sum((f/length) * math.log2(f/length) for f in freq.values())

def measure_time(text, key):
    start_enc = time.time()
    ciphertext = des_encrypt(text, key)
    end_enc = time.time()
    return end_enc - start_enc, ciphertext

# Get 8-character key from user
key_input = input("Enter an 8-character key: ")
if len(key_input) != 8:
    raise ValueError("Key must be exactly 8 characters long!")

key = key_input.encode()  # Convert to bytes

for plaintext in plaintext_sizes:
    enc_time, ciphertext = measure_time(plaintext, key)
    entropy_value = calculate_entropy(ciphertext)

    print(f"\nPlaintext Size: {len(plaintext.encode())} bytes")
    print(f"Ciphertext: {binascii.hexlify(ciphertext).decode()}")
    print(f"Entropy: {entropy_value:.4f}")
    print(f"Encryption Time: {enc_time:.6f} seconds\n")

"""
### Effects of Key and Plaintext Changes on AES Encryption

- **Key & Plaintext Changes:** Small changes in the key or plaintext lead to significantly different ciphertexts, proving AES's strong security.
- **Statistical Analysis:**  
  - Encryption/decryption times increase as plaintext size grows.  
  - Patterns in plaintext can appear in ciphertext, depending on the encryption mode.  
- **Key Length & Modes of Operation:**  
  - AES offers stronger security with 128-bit, 192-bit, and 256-bit keys, unlike DES’s vulnerable 56-bit key.  
  - CBC mode adds randomness, making AES more secure than ECB mode, which exposes plaintext patterns."""